### ISSUE TITLE
Exception Class 코드 리팩토링

### ISSUE THREAD

**Issue by RedJunHee** [RedJunHee/StoreReview#22]
## Steps :mag:
1. Exception 구현체 코드 리딩 중  "ExceptionResponseDto" 객체의 빌드패턴 생성 소스가 겹친다는 것을 발견.
    => "ExceptionResponseDto" 객체의 빌더패턴의 변화가 생길 시 **모든 Exception구현체의 소스 수정 필요**

2. 현재 Exception 구현체들의 Return 메시지는 ApiStatusCode에 정의된 메시지만 정확하게 전달하고있음.
    => PARAMETER_CHECK_FAILED 같은 API 상태코드 또는 앞으로 생길 예외 코드 중. 추가적인 메시지가 필요한 경우가 생길 가능성 있음.

## Description :memo:
1번 이슈에 대해서는  Exception 구현체의 Abstract Type Class를 정의하여 ExceptionResponseDto 빌드패턴 생성 권한 위임하는 방식으로 리팩토링 해 볼 계획입니다.
2번 이슈는  "ExceptionResponseDto.java"에서 
    1.  Meta부분에 추가 메시지를 담는 필드 추가 
    2. getMessage()  부분에서 추가메시지 필드도 같이 String으로 반환

```java
        //msg
        private String error_message =null;
        public String getMessage() { return code.getMessage(); }
```

으로 기능 추가가 될 것 같습니다.

**Comment by BananMoon** [comment]
### 1번 이슈
리팩토링하는 방향은 좋은 것 같습니다. 궁금한 점은 `ExceptionResponseDto` 클래스에 메서드를 정의하여 호출하지않고(아래 코드와 같이) 추상클래스를 정의하는 이유가 따로 있을까요?
```java
public PersonAlreadyExistsException() {
      super();
      exceptionResponseDto = ExceptionResponseDto.buildMetaData(error_code);
}
```

### 2번 이슈
Q. 여러 경우의 메시지들(예_"이메일 형식x", "숫자x")을 담는 필드가 enum타입으로 추가되는 것으로 생각하면 될까요?

**Comment by RedJunHee** [comment]
1번 코멘트에 대해서는 Dto에게 필요한 Code값만 주고 리턴으로 자기 자신을 리턴하는 방법이 더 괜찮네요

 다만, 그렇다면 생성자와 같은 기능과 동일하게 사용되고 빌드패턴의 존재 목적이 희미해지는 상황이라 
ExceptionResponseDto  클래스 자체가 빌드패턴을 빼고 단순하게  일반 클래스와 같은 구조를 가지는건 어떻게 생각하시나요?

2번 코멘트로는 String 타입으로  String extraErrorMessage 같은 필드가 추가되면 될 것 같습니다.

**Comment by RedJunHee** [comment]
개선 방안 테스트버전으로 브런치따서 작성 해봤습니다 

Commit [https://github.com/RedJunHee/StoreReview/commit/9029ad9d09e0c06600e9db06dad5343a9c84f02a]

**Comment by BananMoon** [comment]
네 확인했습니다.
그럼 2번은 파라미터 에러일 때 알려줄 메시지 종류를 정하면 좋을 것 같네요

**Comment by RedJunHee** [comment]
음 메시지 종류를 정하는건  파라미터 예외처리 같은 경우는 벨리데이터에서 나오는 메시지가 담기게 하면 될 것 같고,


추가로 ExceptionResponseDtoTest와 같은  빌더패턴이 아닌 일반 클래스로 ResponseJsonDto도 변경하고자 하는데 어떠신가요

너무 자주 변경되는 것 같긴 한데,   필드가 많이 없어서 빌더패턴보다 간편하게 사용하는게 맞는것 같네요...
빌더패턴을 사용하고 싶어서 욕심을 좀 부려보긴했는데, ㅋㅋ;; 아닌것 같습니다.


확인해주시면 위에 Test버전으로 선 작업 해둔거 개발작업하고 PR올리겠습니다.

**Comment by BananMoon** [comment]
네 빌더패턴 안쓰는게 더 깔끔해서 좋을 것 같네요
