### ISSUE TITLE
API 규격서 OUTPUT 동결 필요

### ISSUE THREAD

**Issue by RedJunHee** [RedJunHee/StoreReview#24]
## Steps :mag:
- API 규격서에 대해 의논이 필요.
- OUTPUT 메시지 동결 후 프론트에 의사 전달 필요.

## Description :memo:
-현재 sign_in, sign_up의 규격서가 작성된 시점에서 OUTPUT 메시지 규격을 동결시키고자 합니다.

## 제안🔵
- OUTPUT 필드 정보
![image](https://user-images.githubusercontent.com/46863381/148485672-252b6572-d957-4b73-97bd-2b2a6795990f.png)

- 성공 메시지
 1. meta 코드만 존재
```text
{ "meta" : { "code" : 200 } }
```
 2.  meta 코드 + data존재
```text
{ 
"meta" : {
 "code" : 200 
}
   “data”: {
        token : eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbjEiLCJhdXRoIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjQxNTIxMjUzfQ._ZXLBfarfi0H1Pb0kXhtclJXz4KNhJ6wkwwjufkQk1q3P1wCy7p7rBxiOadwczonsMMh48mXkYOCIjw8dBB4Jg
   }
 }

```

- 실패 메시지
```text
{ 
"meta" : {
          "code" : 400,
            "error_type" : "Bad Request", 
"error_message" : "문법상 또는 파라미터 오류가 있어서 서버가 요청사항을 처리하지 못함."
     }
 }

```

*** meta 부분만 잘 봐주시며 될 것 같습니다.
성공시에는 code만 존재
실패시에 error_type+ error_message가 추가되는 식.

어떠신가요?

**Comment by BananMoon** [comment]
기존에는 성공시에도 메타데이터에 code, type, message가 들어간 것에서 
성공 시에는 type과 message를 빼자는 의견이신거지요?

**Comment by RedJunHee** [comment]
네 맞습니다
